# /etc/skel/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
[[ -f ~/.bashrc ]] && . ~/.bashrc

export PATH=/home/gooose/.cabal/bin:$PATH
export PATH="/home/gooose/bin/Sencha/Cmd/6.0.2.14/..:$PATH"
