# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

export TERM=xterm-256color
# override default editor for ranger (default is nano)
export EDITOR=vim


# Put your fun stuff here.
PATH=$HOME/.cabal/bin:$HOME/.local/bin:$HOME/bin:$PATH

alias eqf='equery f'
alias equ='equery u'
alias eqh='equery h'
alias eqa='equery a'
alias eqb='equery b'
alias eql='equery l'
alias eqd='equery d'
alias eqg='equery g'
alias eqc='equery c'
alias eqk='equery k'
alias eqm='equery m'
alias eqy='equery y'
alias eqs='equery s'
alias eqw='equery w'

alias ..='cd ..'
alias ...='cd ...'

alias l='ls -l'
alias ll='ls -al'
alias lll='ls -altr'

# fit window size
alias f='feh --scale-down --auto-zoom'

alias current="sudo genlop -c"
 
# installation
# npm install -g diff2html
# emerge -av dev-ruby/bcat
alias bdiff="diff2html -i stdin -o stdout | bcat"

alias lcat="libreoffice --cat"

alias cal="cal -m"
set -o vi

# https://superuser.com/questions/479726/how-to-get-infinite-command-history-in-bash
HISTSIZE="INFINITE"


if [ -f $HOME/.bashrc_additional_config ]; then
    source $HOME/.bashrc_additional_config
fi
