" set nocompatible
filetype off

set wildchar=<Tab> wildmenu wildmode=full

set number

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

" Umlaute
set termencoding=utf8
set enc=utf8
set fileencoding=utf8

highlight Normal guifg=grey guibg=black
colorscheme jellybeans

set expandtab
set cindent

set tabstop=4
set softtabstop=4
set shiftwidth=4

set autoindent
let g:airline#extensions#tabline#enabled = 1

set backup
set backupdir=~/tmp/vim
set dir=~/tmp/vim


set rtp+=~/.vim/bundle/vundle
call vundle#begin()

Plugin 'gmarik/vundle'

" === Plugins! ===

Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim' 
Plugin 'Raimondi/delimitMate'
Plugin 'bling/vim-airline'
Plugin 'majutsushi/tagbar'
Plugin 'vim-scripts/taglist.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/syntastic'
Plugin 'mxw/vim-jsx'

" === Elixir ===

Plugin 'elixir-lang/vim-elixir'
Plugin 'slashmili/alchemist.vim'

" === Erlang ===

Plugin 'vim-erlang/vim-erlang-skeletons'
Plugin 'vim-erlang/vim-erlang-compiler'
Plugin 'vim-erlang/vim-erlang-omnicomplete'
Plugin 'vim-erlang/vim-erlang-runtime'
Plugin 'vim-erlang/vim-erlang-tags'

" === Elm ===

Plugin 'elmcast/elm-vim'

" === Vue ===

Plugin 'posva/vim-vue'

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1

let g:elm_syntastic_show_warnings = 1

" === Misc ===

Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'mileszs/ack.vim'

let g:syntastic_check_on_open=1

call vundle#end()

let g:jsx_ext_required = 0 
let g:syntastic_javascript_checkers = ['eslint']

" recomendet Elm-Vim plugin settings

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list  =1

let g:elm_syntastic_show_warnings = 1

let g:ackprg = 'ag --vimgrep --smart-case'
cnoreabbrev ag Ack
cnoreabbrev aG Ack
cnoreabbrev Ag Ack
cnoreabbrev AG Ack

filetype plugin indent on

syntax on

" == Without this setting cd is impossible
" http://superuser.com/questions/401413/cant-open-folders-in-linux-nerdtree-vim
let NERDTreeDirArrows=0

nmap <F12> :NERDTreeToggle<CR>
nmap <F11> :NERDTreeFind<CR>
nmap <F10> :%!js-beautify -f -<CR>
nmap <C-TAB> :bNext<CR>

nnoremap <silent> ü : exe "vertical resize +5"<CR>
nnoremap <silent> ä : exe "vertical resize -5"<CR>

nnoremap <silent> + : exe "resize +5"<CR>
nnoremap <silent> - : exe "resize -5"<CR>
